# Generated by Django 4.0 on 2021-12-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='English',
        ),
    ]
