# Generated by Django 4.0 on 2021-12-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_aboutus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aboutus',
            new_name='About',
        ),
    ]
